import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Providers } from "@/components/providers";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const fontSans = Inter({
   subsets: ["latin"],
   variable: "--font-sans",
});

const fontMono = JetBrains_Mono({
   subsets: ["latin"],
   variable: "--font-mono",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

type LayoutProps = {
   children: ReactNode;
};

export default async function RootLayout({ children }: LayoutProps) {
   return (
      <html lang="fr" suppressHydrationWarning className="h-full">
         <body
            className={cn(
               fontSans.variable,
               fontMono.variable,
               "antialiased",
               "flex flex-col min-h-full",
            )}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="cosmic-night-dark"
               themes={[
                  "perso",
                  "cosmic-night-dark",
                  "cosmic-night-light",
                  "dark",
                  "system",
               ]}
               disableTransitionOnChange
               enableColorScheme={false}
            >
               <TooltipProvider>
                  <Providers>{children}</Providers>
               </TooltipProvider>
               <Toaster />
            </ThemeProvider>
         </body>
      </html>
   );
}
